//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class buy_list
    {
        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string account { get; set; }
        [DisplayName("產品編號")]
        [Required(ErrorMessage = "產品編號不可空白")]
        [StringLength(5, ErrorMessage = "欄位長度5字內")]
        public string product_id { get; set; }
        [DisplayName("購買流水號")]
        public long quid { get; set; }
        [DisplayName("購買數量")]
        [Range(0, 999)]
        public short number { get; set; } = 0;
        [DisplayName("購買時間")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime datetime { get; set; }
    
        public virtual users users { get; set; }
        public virtual mall mall { get; set; }
    }
}
