//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profile()
        {
            this.profile_log = new HashSet<profile_log>();
            this.users = new HashSet<users>();
        }

        [DisplayName("頭像編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public short profile_id { get; set; }
        [DisplayName("頭像名稱")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string profile_name { get; set; }
        [DisplayName("頭像路徑")]
        [StringLength(400, ErrorMessage = "欄位長度400字內")]
        public string profile_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profile_log> profile_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
    }
}
