//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class quizzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quizzes()
        {
            this.play_record = new HashSet<play_record>();
            this.post = new HashSet<post>();
            this.quiz_answer = new HashSet<quiz_answer>();
            this.quiz_violations = new HashSet<quiz_violations>();
            this.use_record = new HashSet<use_record>();
            this.users = new HashSet<users>();
        }

        [DisplayName("遊戲題目流水號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public int quiz_guid { get; set; }
        [DisplayName("題庫類別編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(1, ErrorMessage = "欄位長度1字內")]
        public string type_id { get; set; }
        [DisplayName("文字題目")]
        [StringLength(100, ErrorMessage = "欄位長度100字內")]
        public string tittle_text { get; set; }
        [DisplayName("圖片題目")]
        [StringLength(200, ErrorMessage = "欄位長度200字內")]
        public string title_img_path { get; set; }
        [DisplayName("影音題目")]
        [StringLength(255, ErrorMessage = "欄位長度255字內")]
        public string title_video_path { get; set; }
        [DisplayName("難易度編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public short difficulty_id { get; set; }
        [DisplayName("答題時間(秒)")]
        [Required(ErrorMessage = "欄位不可空白")]
        [Range(5, 60)]
        public int time { get; set; } = 5;
        [DisplayName("可獲得積分")]
        [Range(0, 100)]
        [Required(ErrorMessage = "欄位不可空白")]
        public short score { get; set; } = 10;
        [DisplayName("需花費精力值")]
        [Required(ErrorMessage = "欄位不可空白")]
        [Range(5, 50)]
        public int energy { get; set; } = 5;
        [DisplayName("是否可見")]
        [Required(ErrorMessage = "欄位不可空白")]
        public bool visible { get; set; } = true;
        [DisplayName("點讚總數")]
        public int like_num { get; set; } = 0;
        [DisplayName("遊戲題組編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public int quiz_group { get; set; }
    
        public virtual difficulty_level difficulty_level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<play_record> play_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_answer> quiz_answer { get; set; }
        public virtual quiz_group quiz_group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_violations> quiz_violations { get; set; }
        public virtual type type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<use_record> use_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
    }
}
