//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public type()
        {
            this.quiz_answer = new HashSet<quiz_answer>();
            this.quizzes = new HashSet<quizzes>();
        }

        [DisplayName("型態編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(1, ErrorMessage = "欄位長度1字內")]
        public string type_id { get; set; }
        [DisplayName("型態描述")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(40, ErrorMessage = "欄位長度40字內")]
        public string type_desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_answer> quiz_answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quizzes> quizzes { get; set; }
    }
}
