//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public announcement()
        {
            this.announcement_log = new HashSet<announcement_log>();
        }

        [DisplayName("公告編號")]
        public int id { get; set; }
        [DisplayName("公告標題")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(100, ErrorMessage = "欄位長度100字內")]
        public string title { get; set; }
        [DisplayName("公告內容")]
        [StringLength(510, ErrorMessage = "欄位長度510字內")]
        public string content { get; set; }
        private DateTime _SetDefaultDate = DateTime.Now;
        [DisplayName("釋出時間")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime publish_time
        {
            get { return _SetDefaultDate; }
            set { _SetDefaultDate = value; }
        }
        //public System.DateTime publish_time { get; set; } = DateTime.Now;
        [DisplayName("優先順序")]
        [Required(ErrorMessage = "欄位不可空白")]
        [Range(0,999)]
        public int priority { get; set; } = 999;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<announcement_log> announcement_log { get; set; }
    }
}
