//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mall()
        {
            this.bag = new HashSet<bag>();
            this.buy_list = new HashSet<buy_list>();
            this.mall_log = new HashSet<mall_log>();
            this.use_record = new HashSet<use_record>();
        }

        [DisplayName("產品編號")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(5, ErrorMessage = "欄位長度5字內")]
        public string product_id { get; set; }
        [DisplayName("產品名稱")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(40, ErrorMessage = "欄位長度40字內")]
        public string product_desc { get; set; }
        [DisplayName("兌換所需積分")]
        [Required(ErrorMessage = "欄位不可空白")]
        public int price { get; set; }
        [DisplayName("是否上架")]
        [Required(ErrorMessage = "欄位不可空白")]
        public bool active { get; set; } = true;
        [DisplayName("產品圖")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(400, ErrorMessage = "欄位長度400字內")]
        public string img_path { get; set; }
        [DisplayName("產品使用效果圖")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(400, ErrorMessage = "欄位長度400字內")]
        public string used_img_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bag> bag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_list> buy_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mall_log> mall_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<use_record> use_record { get; set; }
    }
}
