//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message()
        {
            this.use_record = new HashSet<use_record>();
        }

        [DisplayName("信箱流水號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public long message_guid { get; set; }
        [DisplayName("寄件人")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string from_id { get; set; }
        [DisplayName("收件人")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string to_id { get; set; }
        [DisplayName("內容")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(510, ErrorMessage = "欄位長度510字內")]
        public string msg { get; set; }
        [DisplayName("寄信時間")]
        //[Required(ErrorMessage = "欄位不可空白")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime datetime { get; set; }
        [DisplayName("是否閱讀")]
        public Nullable<bool> read_flag { get; set; }
        [DisplayName("是否刪除")]
        public Nullable<bool> delete_flag { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<use_record> use_record { get; set; }
    }
}
