//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class quiz_violations
    {
        [DisplayName("檢舉流水號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public int violation_quid { get; set; }
        [DisplayName("檢舉人帳號")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string reporter_id { get; set; }
        [DisplayName("遊戲題目流水號")]
        [Required(ErrorMessage = "欄位不可空白")]
        public int quiz_guid { get; set; }
        [DisplayName("管理員帳號")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string manager_id { get; set; }
        [DisplayName("是否檢舉")]
        [Required(ErrorMessage = "欄位不可空白")]
        public bool check_flag { get; set; } = false;
        [DisplayName("檢舉時間")]
        //[Required(ErrorMessage = "欄位不可空白")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime datetime { get; set; }
        [DisplayName("檢舉原因")]
        [Required(ErrorMessage = "欄位不可空白")]
        [StringLength(400, ErrorMessage = "欄位長度400字內")]
        public string violation_reason { get; set; }
    
        public virtual manager manager { get; set; }
        public virtual quizzes quizzes { get; set; }
        public virtual users users { get; set; }
    }
}
