//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeeNowEntities : DbContext
    {
        public SeeNowEntities()
            : base("name=SeeNowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<announcement> announcement { get; set; }
        public virtual DbSet<announcement_log> announcement_log { get; set; }
        public virtual DbSet<bag> bag { get; set; }
        public virtual DbSet<buy_list> buy_list { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<category_log> category_log { get; set; }
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<classes_member> classes_member { get; set; }
        public virtual DbSet<difficulty_level> difficulty_level { get; set; }
        public virtual DbSet<difficulty_level_log> difficulty_level_log { get; set; }
        public virtual DbSet<friendship> friendship { get; set; }
        public virtual DbSet<guardianship> guardianship { get; set; }
        public virtual DbSet<mall> mall { get; set; }
        public virtual DbSet<mall_log> mall_log { get; set; }
        public virtual DbSet<manager> manager { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<play_record> play_record { get; set; }
        public virtual DbSet<play_record_answer> play_record_answer { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<post_violations> post_violations { get; set; }
        public virtual DbSet<profile> profile { get; set; }
        public virtual DbSet<profile_log> profile_log { get; set; }
        public virtual DbSet<quiz_answer> quiz_answer { get; set; }
        public virtual DbSet<quiz_group> quiz_group { get; set; }
        public virtual DbSet<quiz_violations> quiz_violations { get; set; }
        public virtual DbSet<quizzes> quizzes { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_log> role_log { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<use_record> use_record { get; set; }
        public virtual DbSet<user_violations> user_violations { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<setting_menu> setting_menu { get; set; }
        public virtual DbSet<frontend_menu> frontend_menu { get; set; }
    }
}
