//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class use_record
    {
        [DisplayName("使用流水號")]
        public int use_guid { get; set; }
        [DisplayName("帳號")]
        public string account { get; set; }
        [DisplayName("產品編號")]
        public string product_id { get; set; }
        [DisplayName("使用數量")]
        public int used_quantity { get; set; }
        [DisplayName("信箱流水號")]
        public Nullable<long> message_guid { get; set; }
        [DisplayName("遊戲題目流水號")]
        public Nullable<int> quiz_guid { get; set; }
    
        public virtual mall mall { get; set; }
        public virtual message message { get; set; }
        public virtual quizzes quizzes { get; set; }
        public virtual users users { get; set; }
    }
}
