//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
public users()
        {
            this.bag = new HashSet<bag>();
            this.buy_list = new HashSet<buy_list>();
            this.classes = new HashSet<classes>();
            this.classes_member = new HashSet<classes_member>();
            this.friendship = new HashSet<friendship>();
            this.guardianship = new HashSet<guardianship>();
            this.message = new HashSet<message>();
            this.msg = new HashSet<message>();
            this.play_record = new HashSet<play_record>();
            this.post = new HashSet<post>();
            this.post_violations = new HashSet<post_violations>();
            this.quiz_group = new HashSet<quiz_group>();
            this.quiz_violations = new HashSet<quiz_violations>();
            this.use_record = new HashSet<use_record>();
            this.user_violations = new HashSet<user_violations>();
            this.user_violations1 = new HashSet<user_violations>();
            this.quizzes = new HashSet<quizzes>();
        }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [StringLength(20, ErrorMessage = "欄位長度20字內")]
        public string account { get; set; }
        [DisplayName("身分類別編號")]
        [Required(ErrorMessage = "身分類別編號不可空白")]
        public string role_id { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "密碼長度8~20碼")]
        public string password { get; set; }


        //[Display(Name = "確認密碼：")]
        //[DataType(DataType.Password)]
        //////[Required(ErrorMessage = "請您再次輸入密碼！")]
        //////與Password做比對，再次確認使用者輸入的密碼
        ////[NotMapped]
        ////[Compare("password", ErrorMessage = "兩次輸入的密碼必須相符！")]
        //public string ConfirmPassword { get; set; }

        [DisplayName("暱稱")]
        [Required(ErrorMessage = "暱稱不可空白")]
        [StringLength(44, ErrorMessage = "欄位長度44字內")]
        public string nick_name { get; set; }
        [DisplayName("郵箱")]
        [Required(ErrorMessage = "郵箱不可空白")]
        [EmailAddress(ErrorMessage = "郵箱格式錯誤")]
        [StringLength(40, ErrorMessage = "欄位長度40字內")]
        public string e_mail { get; set; }
        [DisplayName("目前積分")]
        public int score { get; set; }
        [DisplayName("目前精力")]
        public int energy { get; set; }
        [DisplayName("頭像")]
        public short profile_id { get; set; }
        [DisplayName("背包格數")]
        public int bag_number { get; set; }
        [DisplayName("是否鎖定")]
        public bool lock_flag { get; set; }
        [DisplayName("是否驗證")]
        public bool validation_flag { get; set; }
        [DisplayName("是否重設密碼")]
        public bool resetable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bag> bag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_list> buy_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classes> classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classes_member> classes_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<friendship> friendship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guardianship> guardianship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> msg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<play_record> play_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_violations> post_violations { get; set; }
        public virtual profile profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_group> quiz_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz_violations> quiz_violations { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<use_record> use_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_violations> user_violations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_violations> user_violations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quizzes> quizzes { get; set; }
    }
}
